{% set name = "pygsl_lite" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygsl_lite-{{ version }}.tar.gz
  sha256: 31b0c24753416d3eacf46cadbfc7aabde38a1e75524931b41e583a0f86fb0517


build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - cython                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - swig >=4.0
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  host:
    - gsl
    - numpy
    - pip
    - python
    - setuptools
    - setuptools-scm >=3.4.3
    - wheel

  run:
    - gsl
    - numpy >=1.23
    - python

test:
  requires:
    - pip
    - pytest
  source_files:
    - test/
  commands:
    - pip check
    - pytest test/


about:
  summary: Minimal GNU Scientific Library Interface
  home: https://pypi.org/project/pygsl-lite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  description: |
    pygsl_lite is a minimal wrapper around GSL based on the pygsl library.
    It contains a small feature set aimed at physics modelling. The reduced
    feature set, as well as supporting only modern GSL versions makes the
    maintenance much simpler for small projects.

extra:
  recipe-maintainers:
    - raffienficiaud
    - lorenzopompili00
    - SergeiOssokine
